//! Tabu search with clique-guided mutation.
//!
//! Implements Exoo-style tabu search adapted for our balanced-pair-flip move shape.
//! Each iteration picks the best (red_flip, blue_flip) pair from a candidate pool
//! generated by sampling surviving k-cliques and high-participation edges, filtered
//! by edge-level tabu memory. Adaptive tenure widens the tabu window on stuck
//! periods; aspiration allows tabu moves that produce a new global best;
//! diversification perturbs the graph and clears tabu when stuck for too long.
//!
//! Design notes (see `docs/investigations/tabu-search-investigation.md`):
//! - Move shape is balanced (1 red flip + 1 blue flip), not single-edge as in
//!   Exoo's papers — our problem requires |red - blue| ∈ {0, 1}.
//! - `CliqueCollection` doesn't support incremental update, so we track destroyed
//!   *original* clique indices in a HashSet (matching the VDS pattern). Candidate
//!   sampling draws from `original ∖ destroyed`. Newly-created cliques are not
//!   tracked individually; their count is reflected in the running clique count
//!   via per-move delta evaluation.

use std::collections::{HashMap, HashSet};

use rand::rngs::StdRng;
use rand::{RngExt, SeedableRng};

use crate::algorithm::{get_cliques_comprehensive, get_new_cliques};
use crate::clique_collection::CliqueCollection;
use crate::graph::{Graph, WorkUnitEdge};
use crate::log_info;

/// Configuration for a tabu run. One run is one work unit.
#[derive(Clone, Debug)]
pub struct TabuConfig {
    pub max_iterations: u64,
    pub base_tabu_tenure: usize,
    pub max_tabu_tenure: usize,
    pub restart_after: u64,
    /// Per-color candidate pool size before pairing. Total pairs evaluated per
    /// iteration is up to `candidate_pool_size^2`, so this is the dominant
    /// per-iteration cost knob.
    pub candidate_pool_size: usize,
    /// Number of balanced pair flips applied on diversification.
    pub diversification_pair_count: usize,
    /// Optional fixed seed for deterministic tests; `None` uses entropy.
    pub random_seed: Option<u64>,
}

/// Result of a single tabu run.
#[derive(Debug)]
pub struct TabuRunResult {
    pub best_graph_bitstring: String,
    pub best_clique_count: i32,
    pub initial_clique_count: i32,
    pub improved: bool,
    pub iterations_completed: u64,
    pub improvements_found: u32,
    pub diversifications_triggered: u32,
}

/// Edge-level tabu list mapping ordered edges to their expiry iteration.
/// Pruning is amortized: lookups are O(1), and we drop expired entries lazily
/// during checks to avoid O(n) scans every iteration.
#[derive(Default)]
struct TabuList {
    entries: HashMap<(u16, u16), u64>,
}

impl TabuList {
    fn new() -> Self {
        TabuList { entries: HashMap::new() }
    }

    fn add(&mut self, edge: &WorkUnitEdge, expiry: u64) {
        let key = ordered_key(edge);
        self.entries.insert(key, expiry);
    }

    fn is_tabu(&self, edge: &WorkUnitEdge, current_iter: u64) -> bool {
        let key = ordered_key(edge);
        match self.entries.get(&key) {
            Some(&expiry) => expiry > current_iter,
            None => false,
        }
    }

    fn clear(&mut self) {
        self.entries.clear();
    }

    /// Drop entries whose expiry is at or before the current iteration.
    /// Called periodically to bound memory growth.
    fn prune_expired(&mut self, current_iter: u64) {
        self.entries.retain(|_, &mut expiry| expiry > current_iter);
    }
}

#[inline]
fn ordered_key(edge: &WorkUnitEdge) -> (u16, u16) {
    if edge.vertex_one < edge.vertex_two {
        (edge.vertex_one, edge.vertex_two)
    } else {
        (edge.vertex_two, edge.vertex_one)
    }
}

/// Tracks which original cliques (by index in the source `CliqueCollection`)
/// have been touched by any move so far this trajectory. Used purely for
/// candidate filtering — clique counts come from per-move delta evaluation.
#[derive(Default)]
struct DestroyedSet {
    set: HashSet<u32>,
}

impl DestroyedSet {
    fn new() -> Self { DestroyedSet { set: HashSet::new() } }
    fn mark(&mut self, idx: u32) { self.set.insert(idx); }
    fn contains(&self, idx: u32) -> bool { self.set.contains(&idx) }
    fn clear(&mut self) { self.set.clear(); }
}

/// Build pools of red and blue edges with per-edge participation scores,
/// derived from the current graph and its (possibly stale) clique collection.
///
/// The pool is the entire edge set partitioned by current color, paired with
/// the participation score the original clique collection assigns. Caller
/// picks top-K from each pool per iteration.
fn build_edge_pools(
    graph: &Graph,
    clique_collection: &CliqueCollection,
) -> (Vec<(WorkUnitEdge, i32)>, Vec<(WorkUnitEdge, i32)>) {
    let n = graph.vertex_count;
    let mut red = Vec::with_capacity(n * (n - 1) / 4);
    let mut blue = Vec::with_capacity(n * (n - 1) / 4);
    for u in 0..n {
        for v in (u + 1)..n {
            let edge = WorkUnitEdge { vertex_one: u as u16, vertex_two: v as u16 };
            let score = clique_collection.get_count_of_cliques_containing_edges(&[edge.clone()]);
            if graph.adjacency[u].get(v) {
                red.push((edge, score));
            } else {
                blue.push((edge, score));
            }
        }
    }
    (red, blue)
}

/// Generate the candidate pool for one iteration.
///
/// Strategy:
///   1. Pick a random surviving original clique. Add its (k choose 2) edges to a
///      seed set. These are guaranteed-impactful: flipping any one breaks at
///      least this clique.
///   2. Add top-N high-participation edges per color from the static pool.
///   3. Filter by current color (red flips must be currently red; blue must be
///      currently blue — we're flipping AWAY from current state).
///   4. Filter out tabu entries (unless aspiration applies, handled in caller).
///   5. Truncate each pool to `candidate_pool_size`.
fn generate_candidates(
    graph: &Graph,
    clique_collection: &CliqueCollection,
    destroyed: &DestroyedSet,
    sorted_red: &[(WorkUnitEdge, i32)],
    sorted_blue: &[(WorkUnitEdge, i32)],
    tabu: &TabuList,
    current_iter: u64,
    config: &TabuConfig,
    rng: &mut StdRng,
) -> (Vec<WorkUnitEdge>, Vec<WorkUnitEdge>) {
    let mut red_pool: Vec<WorkUnitEdge> = Vec::with_capacity(config.candidate_pool_size + 28);
    let mut blue_pool: Vec<WorkUnitEdge> = Vec::with_capacity(config.candidate_pool_size + 28);
    let mut red_seen: HashSet<(u16, u16)> = HashSet::new();
    let mut blue_seen: HashSet<(u16, u16)> = HashSet::new();

    // Seed from a randomly sampled surviving clique.
    let cliques = clique_collection.cliques();
    if !cliques.is_empty() {
        // Try up to a few times to find a non-destroyed clique.
        for _ in 0..8 {
            let idx = rng.random_range(0..cliques.len());
            if destroyed.contains(idx as u32) { continue; }
            let clique = &cliques[idx];
            for i in 0..clique.len() {
                for j in (i + 1)..clique.len() {
                    let u = clique[i].min(clique[j]) as u16;
                    let v = clique[i].max(clique[j]) as u16;
                    let edge = WorkUnitEdge { vertex_one: u, vertex_two: v };
                    let key = (u, v);
                    let is_red = graph.adjacency[u as usize].get(v as usize);
                    if is_red {
                        if red_seen.insert(key) && !tabu.is_tabu(&edge, current_iter) {
                            red_pool.push(edge);
                        }
                    } else if blue_seen.insert(key) && !tabu.is_tabu(&edge, current_iter) {
                        blue_pool.push(edge);
                    }
                }
            }
            break;
        }
    }

    // Top up each pool from the high-participation pre-sorted lists.
    for (edge, _) in sorted_red {
        if red_pool.len() >= config.candidate_pool_size { break; }
        let key = ordered_key(edge);
        if red_seen.insert(key) && !tabu.is_tabu(edge, current_iter) {
            red_pool.push(edge.clone());
        }
    }
    for (edge, _) in sorted_blue {
        if blue_pool.len() >= config.candidate_pool_size { break; }
        let key = ordered_key(edge);
        if blue_seen.insert(key) && !tabu.is_tabu(edge, current_iter) {
            blue_pool.push(edge.clone());
        }
    }

    // Truncate (the seed step may have over-filled the pool).
    red_pool.truncate(config.candidate_pool_size);
    blue_pool.truncate(config.candidate_pool_size);
    (red_pool, blue_pool)
}

/// Evaluate the delta in monochromatic clique count if the given pair were flipped
/// from the current graph. Negative = improvement. Internally restores graph state.
///
/// Uses edge-seeded Bron-Kerbosch via `get_new_cliques`: counts only cliques
/// containing the flipped edges in their pre-flip color (destroyed) and post-flip
/// color (created). This is the same primitive the exhaustive engine uses, and is
/// orders of magnitude cheaper than `get_cliques_comprehensive` on a graph with
/// hundreds of thousands of cliques. Operates on the current graph state directly
/// — no dependency on a static CliqueCollection.
fn evaluate_pair_delta(
    graph: &mut Graph,
    clique_size: usize,
    red: &WorkUnitEdge,
    blue: &WorkUnitEdge,
) -> i32 {
    let edges = [red.clone(), blue.clone()];
    let destroyed = get_new_cliques(graph, clique_size, &edges);
    graph.flip_edges(&edges);
    let created = get_new_cliques(graph, clique_size, &edges);
    graph.flip_edges(&edges);
    created - destroyed
}

/// Pick the best (red, blue) pair from the candidate pools by minimum delta.
/// Returns `None` if either pool is empty.
fn pick_best_move(
    graph: &mut Graph,
    clique_size: usize,
    red_pool: &[WorkUnitEdge],
    blue_pool: &[WorkUnitEdge],
) -> Option<(WorkUnitEdge, WorkUnitEdge, i32)> {
    if red_pool.is_empty() || blue_pool.is_empty() {
        return None;
    }
    let mut best: Option<(WorkUnitEdge, WorkUnitEdge, i32)> = None;
    for r in red_pool {
        for b in blue_pool {
            let delta = evaluate_pair_delta(graph, clique_size, r, b);
            match &best {
                None => best = Some((r.clone(), b.clone(), delta)),
                Some((_, _, d)) if delta < *d => best = Some((r.clone(), b.clone(), delta)),
                _ => {}
            }
        }
    }
    best
}

/// Apply a move and update destroyed-clique tracking.
fn apply_move(
    graph: &mut Graph,
    clique_collection: &CliqueCollection,
    destroyed: &mut DestroyedSet,
    red: &WorkUnitEdge,
    blue: &WorkUnitEdge,
) {
    for c in clique_collection.get_cliques_containing_edge(red) {
        destroyed.mark(*c);
    }
    for c in clique_collection.get_cliques_containing_edge(blue) {
        destroyed.mark(*c);
    }
    graph.flip_edges(&[red.clone(), blue.clone()]);
}

/// Apply a random balanced perturbation: `pair_count` random (red, blue) flips.
/// Used for diversification.
fn diversify(graph: &mut Graph, pair_count: usize, rng: &mut StdRng) {
    let n = graph.vertex_count;
    let mut applied = 0;
    let mut attempts = 0;
    let max_attempts = pair_count * 20;
    while applied < pair_count && attempts < max_attempts {
        attempts += 1;
        let u = rng.random_range(0..n);
        let v = rng.random_range(0..n);
        if u == v { continue; }
        let (a, b) = if u < v { (u, v) } else { (v, u) };
        if !graph.adjacency[a].get(b) { continue; }
        let red = WorkUnitEdge { vertex_one: a as u16, vertex_two: b as u16 };

        let u2 = rng.random_range(0..n);
        let v2 = rng.random_range(0..n);
        if u2 == v2 { continue; }
        let (c, d) = if u2 < v2 { (u2, v2) } else { (v2, u2) };
        if graph.adjacency[c].get(d) { continue; }
        if (a, b) == (c, d) { continue; }
        let blue = WorkUnitEdge { vertex_one: c as u16, vertex_two: d as u16 };

        graph.flip_edges(&[red, blue]);
        applied += 1;
    }
}

/// Run one complete tabu search trajectory starting from `base_graph`.
pub fn run_tabu(
    base_graph: &Graph,
    clique_size: usize,
    config: &TabuConfig,
    clique_collection: &CliqueCollection,
    threshold: Option<i32>,
) -> TabuRunResult {
    let mut graph = Graph::from_bitstring(&base_graph.to_bitstring(), base_graph.vertex_count);
    let mut current_count = get_cliques_comprehensive(&mut graph, clique_size);
    let initial_clique_count = current_count;

    let mut best_count = current_count;
    let mut best_bitstring = graph.to_bitstring();
    let mut improved = false;
    let mut improvements_found: u32 = 0;
    let mut diversifications_triggered: u32 = 0;

    let mut rng: StdRng = match config.random_seed {
        Some(seed) => StdRng::seed_from_u64(seed),
        None => StdRng::from_rng(&mut rand::rng()),
    };

    let mut tabu_red = TabuList::new();
    let mut tabu_blue = TabuList::new();
    let mut destroyed = DestroyedSet::new();
    let mut tenure = config.base_tabu_tenure;
    let mut iter_since_improvement: u64 = 0;

    // Pre-sort static high-participation pools (descending by participation).
    let (mut sorted_red, mut sorted_blue) = build_edge_pools(&graph, clique_collection);
    sorted_red.sort_by(|a, b| b.1.cmp(&a.1));
    sorted_blue.sort_by(|a, b| b.1.cmp(&a.1));

    log_info!(
        "Tabu starting: vertex_count={}, clique_size={}, initial_count={}, max_iter={}, tenure={}, restart_after={}, pool_size={}",
        base_graph.vertex_count, clique_size, initial_clique_count,
        config.max_iterations, config.base_tabu_tenure, config.restart_after, config.candidate_pool_size
    );

    for iter in 0..config.max_iterations {
        // Periodic tabu pruning to bound memory.
        if iter % 256 == 0 {
            tabu_red.prune_expired(iter);
            tabu_blue.prune_expired(iter);
        }

        // Generate red candidates (filtered against tabu).
        let (red_pool, blue_pool) = {
            // Tabu filter is applied inside generate_candidates against tabu_red only
            // for red candidates; we need the same for blue. Do them in two calls
            // by passing the appropriate tabu list each time.
            let (rp, _) = generate_candidates(
                &graph, clique_collection, &destroyed,
                &sorted_red, &sorted_blue, &tabu_red, iter, config, &mut rng,
            );
            let (_, bp) = generate_candidates(
                &graph, clique_collection, &destroyed,
                &sorted_red, &sorted_blue, &tabu_blue, iter, config, &mut rng,
            );
            (rp, bp)
        };

        if red_pool.is_empty() || blue_pool.is_empty() {
            // No legal candidates — diversify and continue.
            diversify(&mut graph, config.diversification_pair_count, &mut rng);
            current_count = get_cliques_comprehensive(&mut graph, clique_size);
            tabu_red.clear();
            tabu_blue.clear();
            destroyed.clear();
            tenure = config.base_tabu_tenure;
            iter_since_improvement = 0;
            diversifications_triggered += 1;
            continue;
        }

        let move_choice = pick_best_move(
            &mut graph, clique_size, &red_pool, &blue_pool,
        );

        let (red, blue, delta) = match move_choice {
            Some(m) => m,
            None => continue,
        };

        // Aspiration: a move producing a new global best is always allowed (this
        // is enforced upstream by candidate filtering, but we double-check here
        // by allowing improvements regardless of any per-move tabu signal).
        let new_count = current_count + delta;

        apply_move(&mut graph, clique_collection, &mut destroyed, &red, &blue);
        current_count = new_count;

        let expiry = iter + tenure as u64;
        tabu_red.add(&red, expiry);
        tabu_blue.add(&blue, expiry);

        if current_count < best_count {
            best_count = current_count;
            best_bitstring = graph.to_bitstring();
            improvements_found += 1;
            iter_since_improvement = 0;
            tenure = config.base_tabu_tenure; // reset on improvement

            let beats_threshold = match threshold {
                None => true,
                Some(t) => current_count < t,
            };
            if beats_threshold {
                improved = true;
            }
        } else {
            iter_since_improvement += 1;
            if iter_since_improvement % 500 == 0 && tenure < config.max_tabu_tenure {
                tenure = ((tenure as f64) * 1.1).ceil() as usize;
                if tenure > config.max_tabu_tenure { tenure = config.max_tabu_tenure; }
            }
        }

        if iter_since_improvement >= config.restart_after {
            diversify(&mut graph, config.diversification_pair_count, &mut rng);
            current_count = get_cliques_comprehensive(&mut graph, clique_size);
            tabu_red.clear();
            tabu_blue.clear();
            destroyed.clear();
            tenure = config.base_tabu_tenure;
            iter_since_improvement = 0;
            diversifications_triggered += 1;
        }
    }

    log_info!(
        "Tabu finished: iters={}, improvements={}, diversifications={}, best_count={}, delta_from_initial={}",
        config.max_iterations, improvements_found, diversifications_triggered,
        best_count, best_count - initial_clique_count
    );

    TabuRunResult {
        best_graph_bitstring: best_bitstring,
        best_clique_count: best_count,
        initial_clique_count,
        improved,
        iterations_completed: config.max_iterations,
        improvements_found,
        diversifications_triggered,
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::algorithm::get_all_cliques;

    fn k5_bitstring() -> String { "1".repeat(10) }

    fn small_config() -> TabuConfig {
        TabuConfig {
            max_iterations: 50,
            base_tabu_tenure: 4,
            max_tabu_tenure: 8,
            restart_after: 20,
            candidate_pool_size: 4,
            diversification_pair_count: 1,
            random_seed: Some(42),
        }
    }

    #[test]
    fn tabu_list_blocks_within_tenure_and_expires() {
        let mut t = TabuList::new();
        let edge = WorkUnitEdge { vertex_one: 0, vertex_two: 5 };
        assert!(!t.is_tabu(&edge, 0));
        t.add(&edge, 10);
        assert!(t.is_tabu(&edge, 0));
        assert!(t.is_tabu(&edge, 9));
        assert!(!t.is_tabu(&edge, 10));
    }

    #[test]
    fn tabu_list_normalizes_edge_orientation() {
        let mut t = TabuList::new();
        let forward = WorkUnitEdge { vertex_one: 3, vertex_two: 7 };
        let reverse = WorkUnitEdge { vertex_one: 7, vertex_two: 3 };
        t.add(&forward, 100);
        assert!(t.is_tabu(&reverse, 50));
    }

    #[test]
    fn tabu_list_prune_drops_expired_entries() {
        let mut t = TabuList::new();
        t.add(&WorkUnitEdge { vertex_one: 0, vertex_two: 1 }, 5);
        t.add(&WorkUnitEdge { vertex_one: 2, vertex_two: 3 }, 50);
        t.prune_expired(10);
        assert_eq!(t.entries.len(), 1);
    }

    #[test]
    fn tabu_list_clear_empties() {
        let mut t = TabuList::new();
        t.add(&WorkUnitEdge { vertex_one: 0, vertex_two: 1 }, 100);
        t.clear();
        assert_eq!(t.entries.len(), 0);
    }

    #[test]
    fn destroyed_set_tracks_membership() {
        let mut d = DestroyedSet::new();
        assert!(!d.contains(5));
        d.mark(5);
        assert!(d.contains(5));
        d.clear();
        assert!(!d.contains(5));
    }

    #[test]
    fn build_edge_pools_partitions_by_color() {
        // P3: edges (0,1) and (1,2) red; (0,2) blue. Bitstring "101".
        let g = Graph::from_bitstring("101", 3);
        let mut g_for_cliques = Graph::from_bitstring("101", 3);
        let cliques = get_all_cliques(&mut g_for_cliques, 2);
        let mut cc = CliqueCollection::new(3);
        cc.set_cliques(cliques, 3);
        let (red, blue) = build_edge_pools(&g, &cc);
        assert_eq!(red.len(), 2);
        assert_eq!(blue.len(), 1);
    }

    #[test]
    fn evaluate_pair_delta_restores_graph_state() {
        // Make a graph with both red and blue edges, then verify evaluate_pair_delta
        // doesn't mutate state.
        let mut g = Graph::from_bitstring(&k5_bitstring(), 5);
        let prep_flip = WorkUnitEdge { vertex_one: 0, vertex_two: 1 };
        g.flip_edges(&[prep_flip]); // (0,1) is now blue
        let mid = g.to_bitstring();
        let blue = WorkUnitEdge { vertex_one: 0, vertex_two: 1 };
        let red = WorkUnitEdge { vertex_one: 2, vertex_two: 3 };
        let _delta = evaluate_pair_delta(&mut g, 5, &red, &blue);
        assert_eq!(g.to_bitstring(), mid, "evaluate_pair_delta must restore graph state");
    }

    #[test]
    fn evaluate_pair_delta_matches_full_recount() {
        // Sanity: incremental delta should equal (count after flip) - (count before).
        let bits = "1110011010";  // 5-vertex, mixed colors
        let mut g = Graph::from_bitstring(bits, 5);
        let red = WorkUnitEdge { vertex_one: 0, vertex_two: 1 };  // currently red
        let blue = WorkUnitEdge { vertex_one: 0, vertex_two: 4 }; // currently blue
        assert!(g.adjacency[0].get(1));
        assert!(!g.adjacency[0].get(4));

        let before_count = get_cliques_comprehensive(&mut g, 4);
        let delta = evaluate_pair_delta(&mut g, 4, &red, &blue);
        g.flip_edges(&[red.clone(), blue.clone()]);
        let after_count = get_cliques_comprehensive(&mut g, 4);
        g.flip_edges(&[red, blue]);  // restore for cleanliness

        assert_eq!(delta, after_count - before_count,
            "incremental delta must equal full-recount delta");
    }

    #[test]
    fn run_tabu_terminates_within_budget() {
        // Build a small graph with some monochromatic cliques to give the
        // search something to work with. Use K5 (1 red 5-clique).
        let g = Graph::from_bitstring(&k5_bitstring(), 5);
        let mut g_for_cc = Graph::from_bitstring(&k5_bitstring(), 5);
        let cliques = get_all_cliques(&mut g_for_cc, 5);
        let mut cc = CliqueCollection::new(5);
        cc.set_cliques(cliques, 5);

        let result = run_tabu(&g, 5, &small_config(), &cc, None);
        assert_eq!(result.iterations_completed, 50);
        // K5 starts at 1 monochromatic 5-clique; tabu should at minimum match
        // or improve — the right balanced pair flip can drop it to 0.
        assert!(result.best_clique_count <= result.initial_clique_count);
    }

    #[test]
    fn run_tabu_finds_improvement_on_k5() {
        // K5 has 1 monochromatic 5-clique. Flipping one edge (red→blue) plus
        // any other edge swap that maintains balance should reach 0 cliques.
        let g = Graph::from_bitstring(&k5_bitstring(), 5);
        let mut g_for_cc = Graph::from_bitstring(&k5_bitstring(), 5);
        let cliques = get_all_cliques(&mut g_for_cc, 5);
        let mut cc = CliqueCollection::new(5);
        cc.set_cliques(cliques, 5);

        // K5 has 10 red edges and 0 blue — there are no blue candidates to flip,
        // so this graph cannot be balanced-pair-flipped to 0 cliques. Use a
        // partially-flipped K5 that has both colors.
        let _ = g;
        let bits = "1110011111";  // 8 red, 2 blue
        let g2 = Graph::from_bitstring(bits, 5);
        let mut g2_cc = Graph::from_bitstring(bits, 5);
        let cliques2 = get_all_cliques(&mut g2_cc, 5);
        let mut cc2 = CliqueCollection::new(5);
        cc2.set_cliques(cliques2, 5);

        let mut cfg = small_config();
        cfg.max_iterations = 200;

        let result = run_tabu(&g2, 5, &cfg, &cc2, None);
        // Algorithm should at least not regress past the initial state.
        assert!(result.best_clique_count <= result.initial_clique_count);
    }

    #[test]
    fn diversify_changes_graph_state() {
        // Need a balanced-ish graph so diversify has both colors to work with.
        let bits = "111000111000111";  // 6-vertex, 9 red 6 blue
        let mut g = Graph::from_bitstring(bits, 6);
        let before = g.to_bitstring();
        let mut rng = StdRng::seed_from_u64(7);
        diversify(&mut g, 3, &mut rng);
        let after = g.to_bitstring();
        assert_ne!(before, after, "diversify should produce a different graph state");
    }
}
